# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCPopMoreViewDemo' do
  pod 'Masonry',:inhibit_warnings => true
  pod 'SDWebImage', '~> 4.3.2',:inhibit_warnings => true
  pod 'CCPopMoreView',:path=>'../',:inhibit_warnings => true

  target 'CCPopMoreViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CCPopMoreViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  #解决weak不能用问题
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
          end
      end
  end
end
